//! Kani proof harness for Solana account: ReclaimEventAccountContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: reclaim_event_account.rs
//! Constraints checked: 5

/// Symbolic representation of the Solana account for verification
struct SymbolicReclaimEventAccountContext {
    payee: u64,
    message_transmitter: u64,
    message_sent_event_data: u64,
}

impl kani::Arbitrary for SymbolicReclaimEventAccountContext {
    fn any() -> Self {
        Self {
            payee: kani::any(),
            message_transmitter: kani::any(),
            message_sent_event_data: kani::any(),
        }
    }
}

/// Verify: payee.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_reclaimeventaccountcontext_constraint_0() {
    let account: SymbolicReclaimEventAccountContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: payee.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ payee.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: payee.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: payee is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_reclaimeventaccountcontext_constraint_1() {
    let account: SymbolicReclaimEventAccountContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: payee is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'payee is writable  /* Account marked as mutable */' */ }, "Invariant violation: payee is writable  /* Account marked as mutable */");
}

/// Verify: message_transmitter is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_reclaimeventaccountcontext_constraint_2() {
    let account: SymbolicReclaimEventAccountContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_transmitter is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_transmitter is writable  /* Account marked as mutable */' */ }, "Invariant violation: message_transmitter is writable  /* Account marked as mutable */");
}

/// Verify: message_sent_event_data is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_reclaimeventaccountcontext_constraint_3() {
    let account: SymbolicReclaimEventAccountContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_sent_event_data is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_sent_event_data is writable  /* Account marked as mutable */' */ }, "Invariant violation: message_sent_event_data is writable  /* Account marked as mutable */");
}

/// Verify: message_sent_event_data custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_reclaimeventaccountcontext_constraint_4() {
    let account: SymbolicReclaimEventAccountContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_sent_event_data custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_sent_event_data custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: message_sent_event_data custom constraint active  /* User-defined constraint applied */");
}

