//! Kani proof harness for Solana account: HandleReceiveMessageContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: handle_receive_message.rs
//! Constraints checked: 12

/// Symbolic representation of the Solana account for verification
struct SymbolicHandleReceiveMessageContext {
    authority_pda: u64,
    token_messenger: u64,
    remote_token_messenger: u64,
    token_minter: u64,
    local_token: u64,
    token_pair: u64,
    recipient_token_account: u64,
    custody_token_account: u64,
    token_program: u64,
}

impl kani::Arbitrary for SymbolicHandleReceiveMessageContext {
    fn any() -> Self {
        Self {
            authority_pda: kani::any(),
            token_messenger: kani::any(),
            remote_token_messenger: kani::any(),
            token_minter: kani::any(),
            local_token: kani::any(),
            token_pair: kani::any(),
            recipient_token_account: kani::any(),
            custody_token_account: kani::any(),
            token_program: kani::any(),
        }
    }
}

/// Verify: authority_pda.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_0() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority_pda.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ authority_pda.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: authority_pda.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: authority_pda PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_1() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority_pda PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'authority_pda PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: authority_pda PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: remote_token_messenger custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_2() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: remote_token_messenger custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'remote_token_messenger custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: remote_token_messenger custom constraint active  /* User-defined constraint applied */");
}

/// Verify: local_token is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_3() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: local_token is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'local_token is writable  /* Account marked as mutable */' */ }, "Invariant violation: local_token is writable  /* Account marked as mutable */");
}

/// Verify: local_token PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_4() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: local_token PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'local_token PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: local_token PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: token_pair PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_5() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token_pair PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'token_pair PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: token_pair PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: token_pair custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_6() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token_pair custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'token_pair custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: token_pair custom constraint active  /* User-defined constraint applied */");
}

/// Verify: recipient_token_account is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_7() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: recipient_token_account is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'recipient_token_account is writable  /* Account marked as mutable */' */ }, "Invariant violation: recipient_token_account is writable  /* Account marked as mutable */");
}

/// Verify: recipient_token_account custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_8() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: recipient_token_account custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'recipient_token_account custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: recipient_token_account custom constraint active  /* User-defined constraint applied */");
}

/// Verify: custody_token_account is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_9() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: custody_token_account is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'custody_token_account is writable  /* Account marked as mutable */' */ }, "Invariant violation: custody_token_account is writable  /* Account marked as mutable */");
}

/// Verify: custody_token_account PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_10() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: custody_token_account PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'custody_token_account PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: custody_token_account PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: custody_token_account custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_handlereceivemessagecontext_constraint_11() {
    let account: SymbolicHandleReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: custody_token_account custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'custody_token_account custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: custody_token_account custom constraint active  /* User-defined constraint applied */");
}

