//! Kani proof: Arithmetic safety for `amount`
//! Auto-generated by kani-verifier — DO NOT EDIT
//! Source: burn_message.rs:method
//! Invariant: All arithmetic in 'amount' must not overflow/underflow

#[cfg(kani)]
mod kani_proofs {
    /// Verify that all arithmetic operations in `amount` are overflow-safe
    /// at the bit-precise u64 level.
    #[kani::proof]
    #[kani::unwind(16)]
    fn proof_amount_arithmetic_safety() {
        // Create symbolic 64-bit inputs
        let a: u64 = kani::any();
        let b: u64 = kani::any();

        // Constrain to realistic token amounts (≤ total SOL supply ~580M SOL = 5.8e17 lamports)
        kani::assume(a <= 580_000_000_000_000_000u64);
        kani::assume(b <= 580_000_000_000_000_000u64);
        kani::assume(a > 0);
        kani::assume(b > 0);

        // Verify addition does not overflow
        if let Some(sum) = a.checked_add(b) {
            kani::assert(sum >= a, "Addition overflow: sum < a");
            kani::assert(sum >= b, "Addition overflow: sum < b");
        }

        // Verify subtraction does not underflow
        if a >= b {
            let diff = a - b;
            kani::assert(diff <= a, "Subtraction underflow: diff > a");
        }

        // Verify multiplication does not overflow
        if let Some(product) = a.checked_mul(b) {
            kani::assert(product / a == b || a == 0, "Multiplication overflow");
        }

        // Verify division does not divide by zero
        kani::assume(b != 0);
        let quotient = a / b;
        kani::assert(quotient <= a, "Division result exceeds dividend");
    }

    /// Verify checked arithmetic wrapper correctness
    #[kani::proof]
    #[kani::unwind(8)]
    fn proof_amount_arithmetic_safety_checked() {
        let a: u64 = kani::any();
        let b: u64 = kani::any();

        // checked_add correctness
        match a.checked_add(b) {
            Some(sum) => {
                kani::assert(sum == a.wrapping_add(b), "checked_add mismatch");
                kani::assert(sum >= a && sum >= b, "checked_add overflow undetected");
            }
            None => {
                // Overflow case: a + b > u64::MAX
                kani::assert(
                    (a as u128) + (b as u128) > u64::MAX as u128,
                    "False overflow detection in checked_add"
                );
            }
        }
    }
}
