//! Kani proof harness for Solana account: SetMaxBurnAmountPerMessageContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: set_max_burn_amount_per_message.rs
//! Constraints checked: 4

/// Symbolic representation of the Solana account for verification
struct SymbolicSetMaxBurnAmountPerMessageContext {
    token_controller: u64,
    token_minter: u64,
    local_token: u64,
}

impl kani::Arbitrary for SymbolicSetMaxBurnAmountPerMessageContext {
    fn any() -> Self {
        Self {
            token_controller: kani::any(),
            token_minter: kani::any(),
            local_token: kani::any(),
        }
    }
}

/// Verify: token_controller.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setmaxburnamountpermessagecontext_constraint_0() {
    let account: SymbolicSetMaxBurnAmountPerMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token_controller.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ token_controller.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: token_controller.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: token_minter has_one constraint enforced  /* Ownership/relationship validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setmaxburnamountpermessagecontext_constraint_1() {
    let account: SymbolicSetMaxBurnAmountPerMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token_minter has_one constraint enforced  /* Ownership/relationship validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'token_minter has_one constraint enforced  /* Ownership/relationship validated */' */ }, "Invariant violation: token_minter has_one constraint enforced  /* Ownership/relationship validated */");
}

/// Verify: local_token is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setmaxburnamountpermessagecontext_constraint_2() {
    let account: SymbolicSetMaxBurnAmountPerMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: local_token is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'local_token is writable  /* Account marked as mutable */' */ }, "Invariant violation: local_token is writable  /* Account marked as mutable */");
}

/// Verify: local_token PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setmaxburnamountpermessagecontext_constraint_3() {
    let account: SymbolicSetMaxBurnAmountPerMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: local_token PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'local_token PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: local_token PDA validated via seeds  /* PDA derivation checked */");
}

