//! Auto-generated Trident fuzz test for ''
//! Generated by Solana Security Swarm — Trident Integration
//!
//! Run with: trident fuzz run fuzz_test

use trident_fuzz::prelude::*;
use anchor_lang::prelude::*;

/// Fuzz account storage for the fuzzing campaign.
#[derive(Default)]
pub struct FuzzAccounts {
    pub owner: AccountId,
    pub token_messenger: AccountId,
    pub token_minter: AccountId,
    pub payer: AccountId,
    pub token_controller: AccountId,
    pub local_token: AccountId,
    pub custody_token_account: AccountId,
    pub local_token_mint: AccountId,
    pub token_program: AccountId,
    pub system_program: AccountId,
    pub pauser: AccountId,
    pub token_pair: AccountId,
    pub payee: AccountId,
    pub custody_token_mint: AccountId,
    pub pending_owner: AccountId,
    pub denylister: AccountId,
    pub denylist_account: AccountId,
    pub remote_token_messenger: AccountId,
    pub event_rent_payer: AccountId,
    pub sender_authority_pda: AccountId,
    pub burn_token_account: AccountId,
    pub message_transmitter: AccountId,
    pub burn_token_mint: AccountId,
    pub message_sent_event_data: AccountId,
    pub message_transmitter_program: AccountId,
    pub token_messenger_minter_program: AccountId,
    pub authority_pda: AccountId,
    pub fee_recipient_token_account: AccountId,
    pub recipient_token_account: AccountId,
    pub upgrade_authority: AccountId,
    pub token_messenger_minter_program_data: AccountId,
    pub min_fee_controller: AccountId,
    pub used_nonce: AccountId,
    pub attester_manager: AccountId,
    pub sender_program: AccountId,
    pub message_transmitter_program_data: AccountId,
    pub caller: AccountId,
    pub receiver: AccountId,
}

#[derive(Default)]
pub struct FuzzTest {
    pub trident: TridentSVM,
    pub fuzz_accounts: FuzzAccounts,
}

impl FuzzTest {
    /// Initialize program state before fuzzing begins.
    #[init]
    fn start(&mut self) {
        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

    }

    /// Fuzz flow for instruction 'update_pauser'
    #[flow]
    fn flow_update_pauser(&mut self) {
        let mut tx = UpdatePauserTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & UpdatePauserParams */);
        self.trident.execute_transaction(&mut tx, Some("update_pauser"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'add_local_token'
    #[flow]
    fn flow_add_local_token(&mut self) {
        let mut tx = AddLocalTokenTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & AddLocalTokenParams */);
        self.trident.execute_transaction(&mut tx, Some("add_local_token"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unpause'
    #[flow]
    fn flow_unpause(&mut self) {
        let mut tx = UnpauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & UnpauseParams */);
        self.trident.execute_transaction(&mut tx, Some("unpause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'link_token_pair'
    #[flow]
    fn flow_link_token_pair(&mut self) {
        let mut tx = LinkTokenPairTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & LinkTokenPairParams */);
        self.trident.execute_transaction(&mut tx, Some("link_token_pair"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unlink_token_pair'
    #[flow]
    fn flow_unlink_token_pair(&mut self) {
        let mut tx = UnlinkTokenPairTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & UninkTokenPairParams */);
        self.trident.execute_transaction(&mut tx, Some("unlink_token_pair"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'remove_local_token'
    #[flow]
    fn flow_remove_local_token(&mut self) {
        let mut tx = RemoveLocalTokenTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & RemoveLocalTokenParams */);
        self.trident.execute_transaction(&mut tx, Some("remove_local_token"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'burn_token_custody'
    #[flow]
    fn flow_burn_token_custody(&mut self) {
        let mut tx = BurnTokenCustodyTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & BurnTokenCustodyParams */);
        self.trident.execute_transaction(&mut tx, Some("burn_token_custody"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_token_controller'
    #[flow]
    fn flow_set_token_controller(&mut self) {
        let mut tx = SetTokenControllerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetTokenControllerParams */);
        self.trident.execute_transaction(&mut tx, Some("set_token_controller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'pause'
    #[flow]
    fn flow_pause(&mut self) {
        let mut tx = PauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & PauseParams */);
        self.trident.execute_transaction(&mut tx, Some("pause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_max_burn_amount_per_message'
    #[flow]
    fn flow_set_max_burn_amount_per_message(&mut self) {
        let mut tx = SetMaxBurnAmountPerMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetMaxBurnAmountPerMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("set_max_burn_amount_per_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'denylist_account'
    #[flow]
    fn flow_denylist_account(&mut self) {
        let mut tx = DenylistAccountTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* DenylistParams */);
        self.trident.execute_transaction(&mut tx, Some("denylist_account"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'undenylist_account'
    #[flow]
    fn flow_undenylist_account(&mut self) {
        let mut tx = UndenylistAccountTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UndenylistParams */);
        self.trident.execute_transaction(&mut tx, Some("undenylist_account"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_denylister'
    #[flow]
    fn flow_update_denylister(&mut self) {
        let mut tx = UpdateDenylisterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UpdateDenylisterParams */);
        self.trident.execute_transaction(&mut tx, Some("update_denylister"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'transfer_ownership'
    #[flow]
    fn flow_transfer_ownership(&mut self) {
        let mut tx = TransferOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* TransferOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("transfer_ownership"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'accept_ownership'
    #[flow]
    fn flow_accept_ownership(&mut self) {
        let mut tx = AcceptOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* AcceptOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("accept_ownership"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'add_remote_token_messenger'
    #[flow]
    fn flow_add_remote_token_messenger(&mut self) {
        let mut tx = AddRemoteTokenMessengerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* AddRemoteTokenMessengerParams */);
        self.trident.execute_transaction(&mut tx, Some("add_remote_token_messenger"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'remove_remote_token_messenger'
    #[flow]
    fn flow_remove_remote_token_messenger(&mut self) {
        let mut tx = RemoveRemoteTokenMessengerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* RemoveRemoteTokenMessengerParams */);
        self.trident.execute_transaction(&mut tx, Some("remove_remote_token_messenger"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_fee_recipient'
    #[flow]
    fn flow_set_fee_recipient(&mut self) {
        let mut tx = SetFeeRecipientTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetFeeRecipientParams */);
        self.trident.execute_transaction(&mut tx, Some("set_fee_recipient"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_min_fee_controller'
    #[flow]
    fn flow_set_min_fee_controller(&mut self) {
        let mut tx = SetMinFeeControllerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetMinFeeControllerParams */);
        self.trident.execute_transaction(&mut tx, Some("set_min_fee_controller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_min_fee'
    #[flow]
    fn flow_set_min_fee(&mut self) {
        let mut tx = SetMinFeeTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetMinFeeParams */);
        self.trident.execute_transaction(&mut tx, Some("set_min_fee"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn'
    #[flow]
    fn flow_deposit_for_burn(&mut self) {
        let mut tx = DepositForBurnTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* DepositForBurnParams */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn_with_hook'
    #[flow]
    fn flow_deposit_for_burn_with_hook(&mut self) {
        let mut tx = DepositForBurnWithHookTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* DepositForBurnWithHookParams */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn_with_hook"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'handle_receive_finalized_message'
    #[flow]
    fn flow_handle_receive_finalized_message(&mut self) {
        let mut tx = HandleReceiveFinalizedMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* HandleReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("handle_receive_finalized_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'handle_receive_unfinalized_message'
    #[flow]
    fn flow_handle_receive_unfinalized_message(&mut self) {
        let mut tx = HandleReceiveUnfinalizedMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* HandleReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("handle_receive_unfinalized_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_token_controller'
    #[flow]
    fn flow_set_token_controller(&mut self) {
        let mut tx = SetTokenControllerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetTokenControllerParams */);
        self.trident.execute_transaction(&mut tx, Some("set_token_controller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'pause'
    #[flow]
    fn flow_pause(&mut self) {
        let mut tx = PauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* PauseParams */);
        self.trident.execute_transaction(&mut tx, Some("pause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unpause'
    #[flow]
    fn flow_unpause(&mut self) {
        let mut tx = UnpauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UnpauseParams */);
        self.trident.execute_transaction(&mut tx, Some("unpause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_pauser'
    #[flow]
    fn flow_update_pauser(&mut self) {
        let mut tx = UpdatePauserTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UpdatePauserParams */);
        self.trident.execute_transaction(&mut tx, Some("update_pauser"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_max_burn_amount_per_message'
    #[flow]
    fn flow_set_max_burn_amount_per_message(&mut self) {
        let mut tx = SetMaxBurnAmountPerMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetMaxBurnAmountPerMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("set_max_burn_amount_per_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'add_local_token'
    #[flow]
    fn flow_add_local_token(&mut self) {
        let mut tx = AddLocalTokenTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* AddLocalTokenParams */);
        self.trident.execute_transaction(&mut tx, Some("add_local_token"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'remove_local_token'
    #[flow]
    fn flow_remove_local_token(&mut self) {
        let mut tx = RemoveLocalTokenTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* RemoveLocalTokenParams */);
        self.trident.execute_transaction(&mut tx, Some("remove_local_token"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'link_token_pair'
    #[flow]
    fn flow_link_token_pair(&mut self) {
        let mut tx = LinkTokenPairTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* LinkTokenPairParams */);
        self.trident.execute_transaction(&mut tx, Some("link_token_pair"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unlink_token_pair'
    #[flow]
    fn flow_unlink_token_pair(&mut self) {
        let mut tx = UnlinkTokenPairTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UninkTokenPairParams */);
        self.trident.execute_transaction(&mut tx, Some("unlink_token_pair"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'burn_token_custody'
    #[flow]
    fn flow_burn_token_custody(&mut self) {
        let mut tx = BurnTokenCustodyTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* BurnTokenCustodyParams */);
        self.trident.execute_transaction(&mut tx, Some("burn_token_custody"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'accept_ownership'
    #[flow]
    fn flow_accept_ownership(&mut self) {
        let mut tx = AcceptOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & AcceptOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("accept_ownership"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'undenylist_account'
    #[flow]
    fn flow_undenylist_account(&mut self) {
        let mut tx = UndenylistAccountTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & UndenylistParams */);
        self.trident.execute_transaction(&mut tx, Some("undenylist_account"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_fee_recipient'
    #[flow]
    fn flow_set_fee_recipient(&mut self) {
        let mut tx = SetFeeRecipientTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetFeeRecipientParams */);
        self.trident.execute_transaction(&mut tx, Some("set_fee_recipient"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn_with_hook'
    #[flow]
    fn flow_deposit_for_burn_with_hook(&mut self) {
        let mut tx = DepositForBurnWithHookTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & DepositForBurnWithHookParams */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn_with_hook"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'add_remote_token_messenger'
    #[flow]
    fn flow_add_remote_token_messenger(&mut self) {
        let mut tx = AddRemoteTokenMessengerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & AddRemoteTokenMessengerParams */);
        self.trident.execute_transaction(&mut tx, Some("add_remote_token_messenger"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'denylist_account'
    #[flow]
    fn flow_denylist_account(&mut self) {
        let mut tx = DenylistAccountTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & DenylistParams */);
        self.trident.execute_transaction(&mut tx, Some("denylist_account"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn'
    #[flow]
    fn flow_deposit_for_burn(&mut self) {
        let mut tx = DepositForBurnTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & DepositForBurnParams */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn_helper'
    #[flow]
    fn flow_deposit_for_burn_helper(&mut self) {
        let mut tx = DepositForBurnHelperTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_amount(rand::random::<u64>());
        tx.set_destination_domain(rand::random::<u32>());
        tx.set_mint_recipient(Pubkey::new_unique());
        tx.set_destination_caller(Pubkey::new_unique());
        tx.set_max_fee(rand::random::<u64>());
        tx.set_min_finality_threshold(rand::random::<u32>());
        tx.set_hook_data(Default::default() /* & Vec < u8 > */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn_helper"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'handle_receive_unfinalized_message'
    #[flow]
    fn flow_handle_receive_unfinalized_message(&mut self) {
        let mut tx = HandleReceiveUnfinalizedMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & HandleReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("handle_receive_unfinalized_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'handle_receive_finalized_message'
    #[flow]
    fn flow_handle_receive_finalized_message(&mut self) {
        let mut tx = HandleReceiveFinalizedMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & HandleReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("handle_receive_finalized_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'handle_receive_message'
    #[flow]
    fn flow_handle_receive_message(&mut self) {
        let mut tx = HandleReceiveMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & HandleReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("handle_receive_message"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_denylister'
    #[flow]
    fn flow_update_denylister(&mut self) {
        let mut tx = UpdateDenylisterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & UpdateDenylisterParams */);
        self.trident.execute_transaction(&mut tx, Some("update_denylister"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_min_fee_controller'
    #[flow]
    fn flow_set_min_fee_controller(&mut self) {
        let mut tx = SetMinFeeControllerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetMinFeeControllerParams */);
        self.trident.execute_transaction(&mut tx, Some("set_min_fee_controller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_min_fee'
    #[flow]
    fn flow_set_min_fee(&mut self) {
        let mut tx = SetMinFeeTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetMinFeeParams */);
        self.trident.execute_transaction(&mut tx, Some("set_min_fee"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'remove_remote_token_messenger'
    #[flow]
    fn flow_remove_remote_token_messenger(&mut self) {
        let mut tx = RemoveRemoteTokenMessengerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & RemoveRemoteTokenMessengerParams */);
        self.trident.execute_transaction(&mut tx, Some("remove_remote_token_messenger"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'transfer_ownership'
    #[flow]
    fn flow_transfer_ownership(&mut self) {
        let mut tx = TransferOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & TransferOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("transfer_ownership"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'transfer_ownership'
    #[flow]
    fn flow_transfer_ownership(&mut self) {
        let mut tx = TransferOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* TransferOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("transfer_ownership"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'accept_ownership'
    #[flow]
    fn flow_accept_ownership(&mut self) {
        let mut tx = AcceptOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* AcceptOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("accept_ownership"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_pauser'
    #[flow]
    fn flow_update_pauser(&mut self) {
        let mut tx = UpdatePauserTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UpdatePauserParams */);
        self.trident.execute_transaction(&mut tx, Some("update_pauser"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_attester_manager'
    #[flow]
    fn flow_update_attester_manager(&mut self) {
        let mut tx = UpdateAttesterManagerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UpdateAttesterManagerParams */);
        self.trident.execute_transaction(&mut tx, Some("update_attester_manager"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'pause'
    #[flow]
    fn flow_pause(&mut self) {
        let mut tx = PauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* PauseParams */);
        self.trident.execute_transaction(&mut tx, Some("pause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unpause'
    #[flow]
    fn flow_unpause(&mut self) {
        let mut tx = UnpauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UnpauseParams */);
        self.trident.execute_transaction(&mut tx, Some("unpause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_max_message_body_size'
    #[flow]
    fn flow_set_max_message_body_size(&mut self) {
        let mut tx = SetMaxMessageBodySizeTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetMaxMessageBodySizeParams */);
        self.trident.execute_transaction(&mut tx, Some("set_max_message_body_size"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'enable_attester'
    #[flow]
    fn flow_enable_attester(&mut self) {
        let mut tx = EnableAttesterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* EnableAttesterParams */);
        self.trident.execute_transaction(&mut tx, Some("enable_attester"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'disable_attester'
    #[flow]
    fn flow_disable_attester(&mut self) {
        let mut tx = DisableAttesterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* DisableAttesterParams */);
        self.trident.execute_transaction(&mut tx, Some("disable_attester"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_signature_threshold'
    #[flow]
    fn flow_set_signature_threshold(&mut self) {
        let mut tx = SetSignatureThresholdTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetSignatureThresholdParams */);
        self.trident.execute_transaction(&mut tx, Some("set_signature_threshold"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'send_message'
    #[flow]
    fn flow_send_message(&mut self) {
        let mut tx = SendMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SendMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("send_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'receive_message'
    #[flow]
    fn flow_receive_message(&mut self) {
        let mut tx = ReceiveMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* ReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("receive_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'reclaim_event_account'
    #[flow]
    fn flow_reclaim_event_account(&mut self) {
        let mut tx = ReclaimEventAccountTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* ReclaimEventAccountParams */);
        self.trident.execute_transaction(&mut tx, Some("reclaim_event_account"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'is_nonce_used'
    #[flow]
    fn flow_is_nonce_used(&mut self) {
        let mut tx = IsNonceUsedTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        self.trident.execute_transaction(&mut tx, Some("is_nonce_used"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'accept_ownership'
    #[flow]
    fn flow_accept_ownership(&mut self) {
        let mut tx = AcceptOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & AcceptOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("accept_ownership"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'is_nonce_used'
    #[flow]
    fn flow_is_nonce_used(&mut self) {
        let mut tx = IsNonceUsedTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        self.trident.execute_transaction(&mut tx, Some("is_nonce_used"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_pauser'
    #[flow]
    fn flow_update_pauser(&mut self) {
        let mut tx = UpdatePauserTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & UpdatePauserParams */);
        self.trident.execute_transaction(&mut tx, Some("update_pauser"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unpause'
    #[flow]
    fn flow_unpause(&mut self) {
        let mut tx = UnpauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & UnpauseParams */);
        self.trident.execute_transaction(&mut tx, Some("unpause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_signature_threshold'
    #[flow]
    fn flow_set_signature_threshold(&mut self) {
        let mut tx = SetSignatureThresholdTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetSignatureThresholdParams */);
        self.trident.execute_transaction(&mut tx, Some("set_signature_threshold"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_attester_manager'
    #[flow]
    fn flow_update_attester_manager(&mut self) {
        let mut tx = UpdateAttesterManagerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & UpdateAttesterManagerParams */);
        self.trident.execute_transaction(&mut tx, Some("update_attester_manager"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'enable_attester'
    #[flow]
    fn flow_enable_attester(&mut self) {
        let mut tx = EnableAttesterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & EnableAttesterParams */);
        self.trident.execute_transaction(&mut tx, Some("enable_attester"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_max_message_body_size'
    #[flow]
    fn flow_set_max_message_body_size(&mut self) {
        let mut tx = SetMaxMessageBodySizeTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetMaxMessageBodySizeParams */);
        self.trident.execute_transaction(&mut tx, Some("set_max_message_body_size"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'reclaim_event_account'
    #[flow]
    fn flow_reclaim_event_account(&mut self) {
        let mut tx = ReclaimEventAccountTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & ReclaimEventAccountParams */);
        self.trident.execute_transaction(&mut tx, Some("reclaim_event_account"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'disable_attester'
    #[flow]
    fn flow_disable_attester(&mut self) {
        let mut tx = DisableAttesterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & DisableAttesterParams */);
        self.trident.execute_transaction(&mut tx, Some("disable_attester"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'send_message'
    #[flow]
    fn flow_send_message(&mut self) {
        let mut tx = SendMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SendMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("send_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'pause'
    #[flow]
    fn flow_pause(&mut self) {
        let mut tx = PauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & PauseParams */);
        self.trident.execute_transaction(&mut tx, Some("pause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'transfer_ownership'
    #[flow]
    fn flow_transfer_ownership(&mut self) {
        let mut tx = TransferOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & TransferOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("transfer_ownership"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'receive_message'
    #[flow]
    fn flow_receive_message(&mut self) {
        let mut tx = ReceiveMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & ReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("receive_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

}
