//! Kani proof harness for Solana account: LogMessage
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 2

/// Symbolic representation of the Solana account for verification
struct SymbolicLogMessage {
    token: u64,
    authority: u64,
}

impl kani::Arbitrary for SymbolicLogMessage {
    fn any() -> Self {
        Self {
            token: kani::any(),
            authority: kani::any(),
        }
    }
}

/// Verify: token custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_logmessage_constraint_0() {
    let account: SymbolicLogMessage = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'token custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: token custom constraint active  /* User-defined constraint applied */");
}

/// Verify: authority.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_logmessage_constraint_1() {
    let account: SymbolicLogMessage = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ authority.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: authority.is_signer == true  /* Anchor Signer type enforces signer check */");
}

