//! Kani proof harness for Solana account: SendMessageContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: send_message.rs
//! Constraints checked: 7

/// Symbolic representation of the Solana account for verification
struct SymbolicSendMessageContext {
    event_rent_payer: u64,
    sender_authority_pda: u64,
    message_transmitter: u64,
    message_sent_event_data: u64,
    sender_program: u64,
    system_program: u64,
}

impl kani::Arbitrary for SymbolicSendMessageContext {
    fn any() -> Self {
        Self {
            event_rent_payer: kani::any(),
            sender_authority_pda: kani::any(),
            message_transmitter: kani::any(),
            message_sent_event_data: kani::any(),
            sender_program: kani::any(),
            system_program: kani::any(),
        }
    }
}

/// Verify: event_rent_payer.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_sendmessagecontext_constraint_0() {
    let account: SymbolicSendMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: event_rent_payer.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ event_rent_payer.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: event_rent_payer.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: event_rent_payer is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_sendmessagecontext_constraint_1() {
    let account: SymbolicSendMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: event_rent_payer is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'event_rent_payer is writable  /* Account marked as mutable */' */ }, "Invariant violation: event_rent_payer is writable  /* Account marked as mutable */");
}

/// Verify: sender_authority_pda.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_sendmessagecontext_constraint_2() {
    let account: SymbolicSendMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: sender_authority_pda.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ sender_authority_pda.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: sender_authority_pda.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: sender_authority_pda PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_sendmessagecontext_constraint_3() {
    let account: SymbolicSendMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: sender_authority_pda PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'sender_authority_pda PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: sender_authority_pda PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: message_transmitter is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_sendmessagecontext_constraint_4() {
    let account: SymbolicSendMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_transmitter is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_transmitter is writable  /* Account marked as mutable */' */ }, "Invariant violation: message_transmitter is writable  /* Account marked as mutable */");
}

/// Verify: message_sent_event_data initialized atomically  /* Account creation validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_sendmessagecontext_constraint_5() {
    let account: SymbolicSendMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_sent_event_data initialized atomically  /* Account creation validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_sent_event_data initialized atomically  /* Account creation validated */' */ }, "Invariant violation: message_sent_event_data initialized atomically  /* Account creation validated */");
}

/// Verify: sender_program custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_sendmessagecontext_constraint_6() {
    let account: SymbolicSendMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: sender_program custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'sender_program custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: sender_program custom constraint active  /* User-defined constraint applied */");
}

