//! Kani proof harness for Solana account: ReceiveMessageContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: receive_message.rs
//! Constraints checked: 7

/// Symbolic representation of the Solana account for verification
struct SymbolicReceiveMessageContext {
    payer: u64,
    caller: u64,
    authority_pda: u64,
    message_transmitter: u64,
    used_nonce: u64,
    receiver: u64,
    system_program: u64,
}

impl kani::Arbitrary for SymbolicReceiveMessageContext {
    fn any() -> Self {
        Self {
            payer: kani::any(),
            caller: kani::any(),
            authority_pda: kani::any(),
            message_transmitter: kani::any(),
            used_nonce: kani::any(),
            receiver: kani::any(),
            system_program: kani::any(),
        }
    }
}

/// Verify: payer.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_receivemessagecontext_constraint_0() {
    let account: SymbolicReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: payer.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ payer.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: payer.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: payer is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_receivemessagecontext_constraint_1() {
    let account: SymbolicReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: payer is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'payer is writable  /* Account marked as mutable */' */ }, "Invariant violation: payer is writable  /* Account marked as mutable */");
}

/// Verify: caller.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_receivemessagecontext_constraint_2() {
    let account: SymbolicReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: caller.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ caller.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: caller.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: authority_pda PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_receivemessagecontext_constraint_3() {
    let account: SymbolicReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority_pda PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'authority_pda PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: authority_pda PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: used_nonce PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_receivemessagecontext_constraint_4() {
    let account: SymbolicReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: used_nonce PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'used_nonce PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: used_nonce PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: used_nonce initialized atomically  /* Account creation validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_receivemessagecontext_constraint_5() {
    let account: SymbolicReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: used_nonce initialized atomically  /* Account creation validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'used_nonce initialized atomically  /* Account creation validated */' */ }, "Invariant violation: used_nonce initialized atomically  /* Account creation validated */");
}

/// Verify: receiver custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_receivemessagecontext_constraint_6() {
    let account: SymbolicReceiveMessageContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: receiver custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'receiver custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: receiver custom constraint active  /* User-defined constraint applied */");
}

