//! Kani proof harness for Solana account: SetMaxMessageBodySizeContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: set_max_message_body_size.rs
//! Constraints checked: 3

/// Symbolic representation of the Solana account for verification
struct SymbolicSetMaxMessageBodySizeContext {
    owner: u64,
    message_transmitter: u64,
}

impl kani::Arbitrary for SymbolicSetMaxMessageBodySizeContext {
    fn any() -> Self {
        Self {
            owner: kani::any(),
            message_transmitter: kani::any(),
        }
    }
}

/// Verify: owner.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setmaxmessagebodysizecontext_constraint_0() {
    let account: SymbolicSetMaxMessageBodySizeContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: owner.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ owner.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: owner.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: message_transmitter is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setmaxmessagebodysizecontext_constraint_1() {
    let account: SymbolicSetMaxMessageBodySizeContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_transmitter is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_transmitter is writable  /* Account marked as mutable */' */ }, "Invariant violation: message_transmitter is writable  /* Account marked as mutable */");
}

/// Verify: message_transmitter has_one constraint enforced  /* Ownership/relationship validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setmaxmessagebodysizecontext_constraint_2() {
    let account: SymbolicSetMaxMessageBodySizeContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_transmitter has_one constraint enforced  /* Ownership/relationship validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_transmitter has_one constraint enforced  /* Ownership/relationship validated */' */ }, "Invariant violation: message_transmitter has_one constraint enforced  /* Ownership/relationship validated */");
}

