//! Kani proof harness for Solana account: IsNonceUsedContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: is_nonce_used.rs
//! Constraints checked: 1

/// Symbolic representation of the Solana account for verification
struct SymbolicIsNonceUsedContext {
    used_nonce: u64,
}

impl kani::Arbitrary for SymbolicIsNonceUsedContext {
    fn any() -> Self {
        Self {
            used_nonce: kani::any(),
        }
    }
}

/// Verify: used_nonce initialized atomically  /* Account creation validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_isnonceusedcontext_constraint_0() {
    let account: SymbolicIsNonceUsedContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: used_nonce initialized atomically  /* Account creation validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'used_nonce initialized atomically  /* Account creation validated */' */ }, "Invariant violation: used_nonce initialized atomically  /* Account creation validated */");
}

