//! Kani proof harness for Solana account: DepositForBurnContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: deposit_for_burn.rs
//! Constraints checked: 16

/// Symbolic representation of the Solana account for verification
struct SymbolicDepositForBurnContext {
    owner: u64,
    event_rent_payer: u64,
    sender_authority_pda: u64,
    burn_token_account: u64,
    denylist_account: u64,
    message_transmitter: u64,
    token_messenger: u64,
    remote_token_messenger: u64,
    token_minter: u64,
    local_token: u64,
    burn_token_mint: u64,
    message_sent_event_data: u64,
    message_transmitter_program: u64,
    token_messenger_minter_program: u64,
    token_program: u64,
    system_program: u64,
}

impl kani::Arbitrary for SymbolicDepositForBurnContext {
    fn any() -> Self {
        Self {
            owner: kani::any(),
            event_rent_payer: kani::any(),
            sender_authority_pda: kani::any(),
            burn_token_account: kani::any(),
            denylist_account: kani::any(),
            message_transmitter: kani::any(),
            token_messenger: kani::any(),
            remote_token_messenger: kani::any(),
            token_minter: kani::any(),
            local_token: kani::any(),
            burn_token_mint: kani::any(),
            message_sent_event_data: kani::any(),
            message_transmitter_program: kani::any(),
            token_messenger_minter_program: kani::any(),
            token_program: kani::any(),
            system_program: kani::any(),
        }
    }
}

/// Verify: owner.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_0() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: owner.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ owner.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: owner.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: event_rent_payer.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_1() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: event_rent_payer.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ event_rent_payer.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: event_rent_payer.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: event_rent_payer is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_2() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: event_rent_payer is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'event_rent_payer is writable  /* Account marked as mutable */' */ }, "Invariant violation: event_rent_payer is writable  /* Account marked as mutable */");
}

/// Verify: sender_authority_pda PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_3() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: sender_authority_pda PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'sender_authority_pda PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: sender_authority_pda PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: burn_token_account is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_4() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: burn_token_account is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'burn_token_account is writable  /* Account marked as mutable */' */ }, "Invariant violation: burn_token_account is writable  /* Account marked as mutable */");
}

/// Verify: burn_token_account has_one constraint enforced  /* Ownership/relationship validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_5() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: burn_token_account has_one constraint enforced  /* Ownership/relationship validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'burn_token_account has_one constraint enforced  /* Ownership/relationship validated */' */ }, "Invariant violation: burn_token_account has_one constraint enforced  /* Ownership/relationship validated */");
}

/// Verify: burn_token_account custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_6() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: burn_token_account custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'burn_token_account custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: burn_token_account custom constraint active  /* User-defined constraint applied */");
}

/// Verify: denylist_account PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_7() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: denylist_account PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'denylist_account PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: denylist_account PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: message_transmitter is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_8() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_transmitter is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_transmitter is writable  /* Account marked as mutable */' */ }, "Invariant violation: message_transmitter is writable  /* Account marked as mutable */");
}

/// Verify: remote_token_messenger custom constraint active  /* User-defined constraint applied */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_9() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: remote_token_messenger custom constraint active  /* User-defined constraint applied */
    kani::assert({ let _ = &account; true /* TODO: encode 'remote_token_messenger custom constraint active  /* User-defined constraint applied */' */ }, "Invariant violation: remote_token_messenger custom constraint active  /* User-defined constraint applied */");
}

/// Verify: local_token is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_10() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: local_token is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'local_token is writable  /* Account marked as mutable */' */ }, "Invariant violation: local_token is writable  /* Account marked as mutable */");
}

/// Verify: local_token PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_11() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: local_token PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'local_token PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: local_token PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: burn_token_mint is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_12() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: burn_token_mint is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'burn_token_mint is writable  /* Account marked as mutable */' */ }, "Invariant violation: burn_token_mint is writable  /* Account marked as mutable */");
}

/// Verify: message_sent_event_data.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_13() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_sent_event_data.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ message_sent_event_data.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: message_sent_event_data.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: message_sent_event_data is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_14() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_sent_event_data is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_sent_event_data is writable  /* Account marked as mutable */' */ }, "Invariant violation: message_sent_event_data is writable  /* Account marked as mutable */");
}

/// Verify: message_sent_event_data initialized atomically  /* Account creation validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_depositforburncontext_constraint_15() {
    let account: SymbolicDepositForBurnContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: message_sent_event_data initialized atomically  /* Account creation validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'message_sent_event_data initialized atomically  /* Account creation validated */' */ }, "Invariant violation: message_sent_event_data initialized atomically  /* Account creation validated */");
}

