//! Kani proof harness for Solana account: AddLocalTokenContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: add_local_token.rs
//! Constraints checked: 8

/// Symbolic representation of the Solana account for verification
struct SymbolicAddLocalTokenContext {
    payer: u64,
    token_controller: u64,
    token_minter: u64,
    local_token: u64,
    custody_token_account: u64,
    local_token_mint: u64,
    token_program: u64,
    system_program: u64,
}

impl kani::Arbitrary for SymbolicAddLocalTokenContext {
    fn any() -> Self {
        Self {
            payer: kani::any(),
            token_controller: kani::any(),
            token_minter: kani::any(),
            local_token: kani::any(),
            custody_token_account: kani::any(),
            local_token_mint: kani::any(),
            token_program: kani::any(),
            system_program: kani::any(),
        }
    }
}

/// Verify: payer.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_addlocaltokencontext_constraint_0() {
    let account: SymbolicAddLocalTokenContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: payer.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ payer.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: payer.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: payer is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_addlocaltokencontext_constraint_1() {
    let account: SymbolicAddLocalTokenContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: payer is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'payer is writable  /* Account marked as mutable */' */ }, "Invariant violation: payer is writable  /* Account marked as mutable */");
}

/// Verify: token_controller.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_addlocaltokencontext_constraint_2() {
    let account: SymbolicAddLocalTokenContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token_controller.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ token_controller.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: token_controller.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: token_minter has_one constraint enforced  /* Ownership/relationship validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_addlocaltokencontext_constraint_3() {
    let account: SymbolicAddLocalTokenContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token_minter has_one constraint enforced  /* Ownership/relationship validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'token_minter has_one constraint enforced  /* Ownership/relationship validated */' */ }, "Invariant violation: token_minter has_one constraint enforced  /* Ownership/relationship validated */");
}

/// Verify: local_token PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_addlocaltokencontext_constraint_4() {
    let account: SymbolicAddLocalTokenContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: local_token PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'local_token PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: local_token PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: local_token initialized atomically  /* Account creation validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_addlocaltokencontext_constraint_5() {
    let account: SymbolicAddLocalTokenContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: local_token initialized atomically  /* Account creation validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'local_token initialized atomically  /* Account creation validated */' */ }, "Invariant violation: local_token initialized atomically  /* Account creation validated */");
}

/// Verify: custody_token_account PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_addlocaltokencontext_constraint_6() {
    let account: SymbolicAddLocalTokenContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: custody_token_account PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'custody_token_account PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: custody_token_account PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: custody_token_account initialized atomically  /* Account creation validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_addlocaltokencontext_constraint_7() {
    let account: SymbolicAddLocalTokenContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: custody_token_account initialized atomically  /* Account creation validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'custody_token_account initialized atomically  /* Account creation validated */' */ }, "Invariant violation: custody_token_account initialized atomically  /* Account creation validated */");
}

