//! Kani proof harness for Solana account: SetMinFeeControllerContext
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: set_min_fee_controller.rs
//! Constraints checked: 3

/// Symbolic representation of the Solana account for verification
struct SymbolicSetMinFeeControllerContext {
    owner: u64,
    token_messenger: u64,
}

impl kani::Arbitrary for SymbolicSetMinFeeControllerContext {
    fn any() -> Self {
        Self {
            owner: kani::any(),
            token_messenger: kani::any(),
        }
    }
}

/// Verify: owner.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setminfeecontrollercontext_constraint_0() {
    let account: SymbolicSetMinFeeControllerContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: owner.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ owner.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: owner.is_signer == true  /* Anchor Signer type enforces signer check */");
}

/// Verify: token_messenger is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setminfeecontrollercontext_constraint_1() {
    let account: SymbolicSetMinFeeControllerContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token_messenger is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'token_messenger is writable  /* Account marked as mutable */' */ }, "Invariant violation: token_messenger is writable  /* Account marked as mutable */");
}

/// Verify: token_messenger has_one constraint enforced  /* Ownership/relationship validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_setminfeecontrollercontext_constraint_2() {
    let account: SymbolicSetMinFeeControllerContext = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: token_messenger has_one constraint enforced  /* Ownership/relationship validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'token_messenger has_one constraint enforced  /* Ownership/relationship validated */' */ }, "Invariant violation: token_messenger has_one constraint enforced  /* Ownership/relationship validated */");
}

