//! Kani proof harness for Solana account: WithdrawTokens
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 3

/// Symbolic representation of the Solana account for verification
struct SymbolicWithdrawTokens {
    pool: u64,
    vault: u64,
    withdraw_destination: u64,
    authority: u64,
    token_program: u64,
}

impl kani::Arbitrary for SymbolicWithdrawTokens {
    fn any() -> Self {
        Self {
            pool: kani::any(),
            vault: kani::any(),
            withdraw_destination: kani::any(),
            authority: kani::any(),
            token_program: kani::any(),
        }
    }
}

/// Verify: pool has_one constraint enforced  /* Ownership/relationship validated */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdrawtokens_constraint_0() {
    let account: SymbolicWithdrawTokens = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: pool has_one constraint enforced  /* Ownership/relationship validated */
    kani::assert({ let _ = &account; true /* TODO: encode 'pool has_one constraint enforced  /* Ownership/relationship validated */' */ }, "Invariant violation: pool has_one constraint enforced  /* Ownership/relationship validated */");
}

/// Verify: pool PDA validated via seeds  /* PDA derivation checked */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdrawtokens_constraint_1() {
    let account: SymbolicWithdrawTokens = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: pool PDA validated via seeds  /* PDA derivation checked */
    kani::assert({ let _ = &account; true /* TODO: encode 'pool PDA validated via seeds  /* PDA derivation checked */' */ }, "Invariant violation: pool PDA validated via seeds  /* PDA derivation checked */");
}

/// Verify: authority.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdrawtokens_constraint_2() {
    let account: SymbolicWithdrawTokens = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ authority.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: authority.is_signer == true  /* Anchor Signer type enforces signer check */");
}

