//! Auto-generated Trident fuzz test for ''
//! Generated by Solana Security Swarm — Trident Integration
//!
//! Run with: trident fuzz run fuzz_test

use trident_fuzz::prelude::*;
use anchor_lang::prelude::*;

/// Fuzz account storage for the fuzzing campaign.
#[derive(Default)]
pub struct FuzzAccounts {
    pub pending_owner: AccountId,
    pub message_transmitter: AccountId,
    pub used_nonces: AccountId,
    pub owner: AccountId,
    pub pauser: AccountId,
    pub attester_manager: AccountId,
    pub payer: AccountId,
    pub system_program: AccountId,
    pub payee: AccountId,
    pub message_sent_event_data: AccountId,
    pub event_rent_payer: AccountId,
    pub sender_authority_pda: AccountId,
    pub sender_program: AccountId,
    pub upgrade_authority: AccountId,
    pub message_transmitter_program_data: AccountId,
    pub message_transmitter_program: AccountId,
    pub caller: AccountId,
    pub authority_pda: AccountId,
    pub receiver: AccountId,
}

#[derive(Default)]
pub struct FuzzTest {
    pub trident: TridentSVM,
    pub fuzz_accounts: FuzzAccounts,
}

impl FuzzTest {
    /// Initialize program state before fuzzing begins.
    #[init]
    fn start(&mut self) {
        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

    }

    /// Fuzz flow for instruction 'transfer_ownership'
    #[flow]
    fn flow_transfer_ownership(&mut self) {
        let mut tx = TransferOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* TransferOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("transfer_ownership"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'accept_ownership'
    #[flow]
    fn flow_accept_ownership(&mut self) {
        let mut tx = AcceptOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* AcceptOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("accept_ownership"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_pauser'
    #[flow]
    fn flow_update_pauser(&mut self) {
        let mut tx = UpdatePauserTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UpdatePauserParams */);
        self.trident.execute_transaction(&mut tx, Some("update_pauser"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_attester_manager'
    #[flow]
    fn flow_update_attester_manager(&mut self) {
        let mut tx = UpdateAttesterManagerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UpdateAttesterManagerParams */);
        self.trident.execute_transaction(&mut tx, Some("update_attester_manager"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'pause'
    #[flow]
    fn flow_pause(&mut self) {
        let mut tx = PauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* PauseParams */);
        self.trident.execute_transaction(&mut tx, Some("pause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unpause'
    #[flow]
    fn flow_unpause(&mut self) {
        let mut tx = UnpauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UnpauseParams */);
        self.trident.execute_transaction(&mut tx, Some("unpause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_max_message_body_size'
    #[flow]
    fn flow_set_max_message_body_size(&mut self) {
        let mut tx = SetMaxMessageBodySizeTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetMaxMessageBodySizeParams */);
        self.trident.execute_transaction(&mut tx, Some("set_max_message_body_size"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'enable_attester'
    #[flow]
    fn flow_enable_attester(&mut self) {
        let mut tx = EnableAttesterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* EnableAttesterParams */);
        self.trident.execute_transaction(&mut tx, Some("enable_attester"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'disable_attester'
    #[flow]
    fn flow_disable_attester(&mut self) {
        let mut tx = DisableAttesterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* DisableAttesterParams */);
        self.trident.execute_transaction(&mut tx, Some("disable_attester"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_signature_threshold'
    #[flow]
    fn flow_set_signature_threshold(&mut self) {
        let mut tx = SetSignatureThresholdTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetSignatureThresholdParams */);
        self.trident.execute_transaction(&mut tx, Some("set_signature_threshold"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'send_message'
    #[flow]
    fn flow_send_message(&mut self) {
        let mut tx = SendMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SendMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("send_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'send_message_with_caller'
    #[flow]
    fn flow_send_message_with_caller(&mut self) {
        let mut tx = SendMessageWithCallerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SendMessageWithCallerParams */);
        self.trident.execute_transaction(&mut tx, Some("send_message_with_caller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'replace_message'
    #[flow]
    fn flow_replace_message(&mut self) {
        let mut tx = ReplaceMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* ReplaceMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("replace_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'receive_message'
    #[flow]
    fn flow_receive_message(&mut self) {
        let mut tx = ReceiveMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* ReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("receive_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'reclaim_event_account'
    #[flow]
    fn flow_reclaim_event_account(&mut self) {
        let mut tx = ReclaimEventAccountTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* ReclaimEventAccountParams */);
        self.trident.execute_transaction(&mut tx, Some("reclaim_event_account"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'get_nonce_pda'
    #[flow]
    fn flow_get_nonce_pda(&mut self) {
        let mut tx = GetNoncePdaTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* GetNoncePDAParams */);
        self.trident.execute_transaction(&mut tx, Some("get_nonce_pda"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'is_nonce_used'
    #[flow]
    fn flow_is_nonce_used(&mut self) {
        let mut tx = IsNonceUsedTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* IsNonceUsedParams */);
        self.trident.execute_transaction(&mut tx, Some("is_nonce_used"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'accept_ownership'
    #[flow]
    fn flow_accept_ownership(&mut self) {
        let mut tx = AcceptOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & AcceptOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("accept_ownership"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'is_nonce_used'
    #[flow]
    fn flow_is_nonce_used(&mut self) {
        let mut tx = IsNonceUsedTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & IsNonceUsedParams */);
        self.trident.execute_transaction(&mut tx, Some("is_nonce_used"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_pauser'
    #[flow]
    fn flow_update_pauser(&mut self) {
        let mut tx = UpdatePauserTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & UpdatePauserParams */);
        self.trident.execute_transaction(&mut tx, Some("update_pauser"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unpause'
    #[flow]
    fn flow_unpause(&mut self) {
        let mut tx = UnpauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & UnpauseParams */);
        self.trident.execute_transaction(&mut tx, Some("unpause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_signature_threshold'
    #[flow]
    fn flow_set_signature_threshold(&mut self) {
        let mut tx = SetSignatureThresholdTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetSignatureThresholdParams */);
        self.trident.execute_transaction(&mut tx, Some("set_signature_threshold"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_attester_manager'
    #[flow]
    fn flow_update_attester_manager(&mut self) {
        let mut tx = UpdateAttesterManagerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & UpdateAttesterManagerParams */);
        self.trident.execute_transaction(&mut tx, Some("update_attester_manager"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'get_nonce_pda'
    #[flow]
    fn flow_get_nonce_pda(&mut self) {
        let mut tx = GetNoncePdaTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & GetNoncePDAParams */);
        self.trident.execute_transaction(&mut tx, Some("get_nonce_pda"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'enable_attester'
    #[flow]
    fn flow_enable_attester(&mut self) {
        let mut tx = EnableAttesterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & EnableAttesterParams */);
        self.trident.execute_transaction(&mut tx, Some("enable_attester"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_max_message_body_size'
    #[flow]
    fn flow_set_max_message_body_size(&mut self) {
        let mut tx = SetMaxMessageBodySizeTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetMaxMessageBodySizeParams */);
        self.trident.execute_transaction(&mut tx, Some("set_max_message_body_size"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'send_message_with_caller'
    #[flow]
    fn flow_send_message_with_caller(&mut self) {
        let mut tx = SendMessageWithCallerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SendMessageWithCallerParams */);
        self.trident.execute_transaction(&mut tx, Some("send_message_with_caller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'reclaim_event_account'
    #[flow]
    fn flow_reclaim_event_account(&mut self) {
        let mut tx = ReclaimEventAccountTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & ReclaimEventAccountParams */);
        self.trident.execute_transaction(&mut tx, Some("reclaim_event_account"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'disable_attester'
    #[flow]
    fn flow_disable_attester(&mut self) {
        let mut tx = DisableAttesterTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & DisableAttesterParams */);
        self.trident.execute_transaction(&mut tx, Some("disable_attester"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'send_message'
    #[flow]
    fn flow_send_message(&mut self) {
        let mut tx = SendMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SendMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("send_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'pause'
    #[flow]
    fn flow_pause(&mut self) {
        let mut tx = PauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & PauseParams */);
        self.trident.execute_transaction(&mut tx, Some("pause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'transfer_ownership'
    #[flow]
    fn flow_transfer_ownership(&mut self) {
        let mut tx = TransferOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & TransferOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("transfer_ownership"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'receive_message'
    #[flow]
    fn flow_receive_message(&mut self) {
        let mut tx = ReceiveMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & ReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("receive_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'replace_message'
    #[flow]
    fn flow_replace_message(&mut self) {
        let mut tx = ReplaceMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & ReplaceMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("replace_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

}
