//! Kani proof harness for Solana account: Initialize
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 1

/// Symbolic representation of the Solana account for verification
struct SymbolicInitialize {
    user: u64,
    authority: u64,
}

impl kani::Arbitrary for SymbolicInitialize {
    fn any() -> Self {
        Self {
            user: kani::any(),
            authority: kani::any(),
        }
    }
}

/// Verify: authority.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_initialize_constraint_0() {
    let account: SymbolicInitialize = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ authority.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: authority.is_signer == true  /* Anchor Signer type enforces signer check */");
}

