//! Auto-generated Trident fuzz test for ''
//! Generated by Solana Security Swarm — Trident Integration
//!
//! Run with: trident fuzz run fuzz_test

use trident_fuzz::prelude::*;
use anchor_lang::prelude::*;

/// Fuzz account storage for the fuzzing campaign.
#[derive(Default)]
pub struct FuzzAccounts {
    pub user: AccountId,
    pub authority: AccountId,
    pub system_program: AccountId,
}

#[derive(Default)]
pub struct FuzzTest {
    pub trident: TridentSVM,
    pub fuzz_accounts: FuzzAccounts,
}

impl FuzzTest {
    /// Initialize program state before fuzzing begins.
    #[init]
    fn start(&mut self) {
        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

        // Initialize via 'init'
        let mut tx = InitTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("init"));

    }

}
