//! Kani proof harness for Solana account: Cpi
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 1

/// Symbolic representation of the Solana account for verification
struct SymbolicCpi {
    source: u64,
    destination: u64,
    authority: u64,
    token_program: u64,
}

impl kani::Arbitrary for SymbolicCpi {
    fn any() -> Self {
        Self {
            source: kani::any(),
            destination: kani::any(),
            authority: kani::any(),
            token_program: kani::any(),
        }
    }
}

/// Verify: authority.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_cpi_constraint_0() {
    let account: SymbolicCpi = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ authority.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: authority.is_signer == true  /* Anchor Signer type enforces signer check */");
}

