//! Auto-generated Trident fuzz test for ''
//! Generated by Solana Security Swarm — Trident Integration
//!
//! Run with: trident fuzz run fuzz_test

use trident_fuzz::prelude::*;
use anchor_lang::prelude::*;

/// Fuzz account storage for the fuzzing campaign.
#[derive(Default)]
pub struct FuzzAccounts {
    pub pending_owner: AccountId,
    pub token_messenger: AccountId,
    pub payer: AccountId,
    pub owner: AccountId,
    pub remote_token_messenger: AccountId,
    pub system_program: AccountId,
    pub authority_pda: AccountId,
    pub token_minter: AccountId,
    pub local_token: AccountId,
    pub token_pair: AccountId,
    pub recipient_token_account: AccountId,
    pub custody_token_account: AccountId,
    pub token_program: AccountId,
    pub event_rent_payer: AccountId,
    pub sender_authority_pda: AccountId,
    pub burn_token_account: AccountId,
    pub message_transmitter: AccountId,
    pub burn_token_mint: AccountId,
    pub message_sent_event_data: AccountId,
    pub message_transmitter_program: AccountId,
    pub token_messenger_minter_program: AccountId,
    pub upgrade_authority: AccountId,
    pub token_messenger_minter_program_data: AccountId,
    pub payee: AccountId,
    pub token_controller: AccountId,
    pub local_token_mint: AccountId,
    pub pauser: AccountId,
    pub custody_token_mint: AccountId,
}

#[derive(Default)]
pub struct FuzzTest {
    pub trident: TridentSVM,
    pub fuzz_accounts: FuzzAccounts,
}

impl FuzzTest {
    /// Initialize program state before fuzzing begins.
    #[init]
    fn start(&mut self) {
        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

        // Initialize via 'initialize'
        let mut tx = InitializeTransaction::build(&mut self.trident, &mut self.fuzz_accounts);
        self.trident.execute_transaction(&mut tx, Some("initialize"));

    }

    /// Fuzz flow for instruction 'transfer_ownership'
    #[flow]
    fn flow_transfer_ownership(&mut self) {
        let mut tx = TransferOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* TransferOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("transfer_ownership"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'accept_ownership'
    #[flow]
    fn flow_accept_ownership(&mut self) {
        let mut tx = AcceptOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* AcceptOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("accept_ownership"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'add_remote_token_messenger'
    #[flow]
    fn flow_add_remote_token_messenger(&mut self) {
        let mut tx = AddRemoteTokenMessengerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* AddRemoteTokenMessengerParams */);
        self.trident.execute_transaction(&mut tx, Some("add_remote_token_messenger"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'remove_remote_token_messenger'
    #[flow]
    fn flow_remove_remote_token_messenger(&mut self) {
        let mut tx = RemoveRemoteTokenMessengerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* RemoveRemoteTokenMessengerParams */);
        self.trident.execute_transaction(&mut tx, Some("remove_remote_token_messenger"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn'
    #[flow]
    fn flow_deposit_for_burn(&mut self) {
        let mut tx = DepositForBurnTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* DepositForBurnParams */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn_with_caller'
    #[flow]
    fn flow_deposit_for_burn_with_caller(&mut self) {
        let mut tx = DepositForBurnWithCallerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* DepositForBurnWithCallerParams */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn_with_caller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'replace_deposit_for_burn'
    #[flow]
    fn flow_replace_deposit_for_burn(&mut self) {
        let mut tx = ReplaceDepositForBurnTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* ReplaceDepositForBurnParams */);
        self.trident.execute_transaction(&mut tx, Some("replace_deposit_for_burn"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'handle_receive_message'
    #[flow]
    fn flow_handle_receive_message(&mut self) {
        let mut tx = HandleReceiveMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* HandleReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("handle_receive_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_token_controller'
    #[flow]
    fn flow_set_token_controller(&mut self) {
        let mut tx = SetTokenControllerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetTokenControllerParams */);
        self.trident.execute_transaction(&mut tx, Some("set_token_controller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'pause'
    #[flow]
    fn flow_pause(&mut self) {
        let mut tx = PauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* PauseParams */);
        self.trident.execute_transaction(&mut tx, Some("pause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unpause'
    #[flow]
    fn flow_unpause(&mut self) {
        let mut tx = UnpauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UnpauseParams */);
        self.trident.execute_transaction(&mut tx, Some("unpause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_pauser'
    #[flow]
    fn flow_update_pauser(&mut self) {
        let mut tx = UpdatePauserTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UpdatePauserParams */);
        self.trident.execute_transaction(&mut tx, Some("update_pauser"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_max_burn_amount_per_message'
    #[flow]
    fn flow_set_max_burn_amount_per_message(&mut self) {
        let mut tx = SetMaxBurnAmountPerMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* SetMaxBurnAmountPerMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("set_max_burn_amount_per_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'add_local_token'
    #[flow]
    fn flow_add_local_token(&mut self) {
        let mut tx = AddLocalTokenTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* AddLocalTokenParams */);
        self.trident.execute_transaction(&mut tx, Some("add_local_token"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'remove_local_token'
    #[flow]
    fn flow_remove_local_token(&mut self) {
        let mut tx = RemoveLocalTokenTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* RemoveLocalTokenParams */);
        self.trident.execute_transaction(&mut tx, Some("remove_local_token"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'link_token_pair'
    #[flow]
    fn flow_link_token_pair(&mut self) {
        let mut tx = LinkTokenPairTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* LinkTokenPairParams */);
        self.trident.execute_transaction(&mut tx, Some("link_token_pair"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unlink_token_pair'
    #[flow]
    fn flow_unlink_token_pair(&mut self) {
        let mut tx = UnlinkTokenPairTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* UninkTokenPairParams */);
        self.trident.execute_transaction(&mut tx, Some("unlink_token_pair"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'burn_token_custody'
    #[flow]
    fn flow_burn_token_custody(&mut self) {
        let mut tx = BurnTokenCustodyTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* BurnTokenCustodyParams */);
        self.trident.execute_transaction(&mut tx, Some("burn_token_custody"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'accept_ownership'
    #[flow]
    fn flow_accept_ownership(&mut self) {
        let mut tx = AcceptOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & AcceptOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("accept_ownership"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'add_remote_token_messenger'
    #[flow]
    fn flow_add_remote_token_messenger(&mut self) {
        let mut tx = AddRemoteTokenMessengerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & AddRemoteTokenMessengerParams */);
        self.trident.execute_transaction(&mut tx, Some("add_remote_token_messenger"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'handle_receive_message'
    #[flow]
    fn flow_handle_receive_message(&mut self) {
        let mut tx = HandleReceiveMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & HandleReceiveMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("handle_receive_message"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn'
    #[flow]
    fn flow_deposit_for_burn(&mut self) {
        let mut tx = DepositForBurnTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & DepositForBurnParams */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn_helper'
    #[flow]
    fn flow_deposit_for_burn_helper(&mut self) {
        let mut tx = DepositForBurnHelperTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_amount(rand::random::<u64>());
        tx.set_destination_domain(rand::random::<u32>());
        tx.set_mint_recipient(Pubkey::new_unique());
        tx.set_destination_caller(Pubkey::new_unique());
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn_helper"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'deposit_for_burn_with_caller'
    #[flow]
    fn flow_deposit_for_burn_with_caller(&mut self) {
        let mut tx = DepositForBurnWithCallerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & DepositForBurnWithCallerParams */);
        self.trident.execute_transaction(&mut tx, Some("deposit_for_burn_with_caller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'remove_remote_token_messenger'
    #[flow]
    fn flow_remove_remote_token_messenger(&mut self) {
        let mut tx = RemoveRemoteTokenMessengerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & RemoveRemoteTokenMessengerParams */);
        self.trident.execute_transaction(&mut tx, Some("remove_remote_token_messenger"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'transfer_ownership'
    #[flow]
    fn flow_transfer_ownership(&mut self) {
        let mut tx = TransferOwnershipTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & TransferOwnershipParams */);
        self.trident.execute_transaction(&mut tx, Some("transfer_ownership"));

        // Property: balance conservation check
        // assert!(pre_balance >= post_balance || authorized_mint);

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'replace_deposit_for_burn'
    #[flow]
    fn flow_replace_deposit_for_burn(&mut self) {
        let mut tx = ReplaceDepositForBurnTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & ReplaceDepositForBurnParams */);
        self.trident.execute_transaction(&mut tx, Some("replace_deposit_for_burn"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'update_pauser'
    #[flow]
    fn flow_update_pauser(&mut self) {
        let mut tx = UpdatePauserTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & UpdatePauserParams */);
        self.trident.execute_transaction(&mut tx, Some("update_pauser"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'add_local_token'
    #[flow]
    fn flow_add_local_token(&mut self) {
        let mut tx = AddLocalTokenTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & AddLocalTokenParams */);
        self.trident.execute_transaction(&mut tx, Some("add_local_token"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unpause'
    #[flow]
    fn flow_unpause(&mut self) {
        let mut tx = UnpauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & UnpauseParams */);
        self.trident.execute_transaction(&mut tx, Some("unpause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'link_token_pair'
    #[flow]
    fn flow_link_token_pair(&mut self) {
        let mut tx = LinkTokenPairTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & LinkTokenPairParams */);
        self.trident.execute_transaction(&mut tx, Some("link_token_pair"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'unlink_token_pair'
    #[flow]
    fn flow_unlink_token_pair(&mut self) {
        let mut tx = UnlinkTokenPairTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & UninkTokenPairParams */);
        self.trident.execute_transaction(&mut tx, Some("unlink_token_pair"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'remove_local_token'
    #[flow]
    fn flow_remove_local_token(&mut self) {
        let mut tx = RemoveLocalTokenTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & RemoveLocalTokenParams */);
        self.trident.execute_transaction(&mut tx, Some("remove_local_token"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'burn_token_custody'
    #[flow]
    fn flow_burn_token_custody(&mut self) {
        let mut tx = BurnTokenCustodyTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & BurnTokenCustodyParams */);
        self.trident.execute_transaction(&mut tx, Some("burn_token_custody"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_token_controller'
    #[flow]
    fn flow_set_token_controller(&mut self) {
        let mut tx = SetTokenControllerTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetTokenControllerParams */);
        self.trident.execute_transaction(&mut tx, Some("set_token_controller"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'pause'
    #[flow]
    fn flow_pause(&mut self) {
        let mut tx = PauseTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set__params(Default::default() /* & PauseParams */);
        self.trident.execute_transaction(&mut tx, Some("pause"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

    /// Fuzz flow for instruction 'set_max_burn_amount_per_message'
    #[flow]
    fn flow_set_max_burn_amount_per_message(&mut self) {
        let mut tx = SetMaxBurnAmountPerMessageTransaction::build(
            &mut self.trident,
            &mut self.fuzz_accounts,
        );
        tx.set_params(Default::default() /* & SetMaxBurnAmountPerMessageParams */);
        self.trident.execute_transaction(&mut tx, Some("set_max_burn_amount_per_message"));

        // Property: no arithmetic overflow
        // Trident monitors for panics from unchecked math
    }

}
