//! Kani proof harness for Solana account: Vote
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 2

/// Symbolic representation of the Solana account for verification
struct SymbolicVote {
    proposal: u64,
    voter: u64,
}

impl kani::Arbitrary for SymbolicVote {
    fn any() -> Self {
        Self {
            proposal: kani::any(),
            voter: kani::any(),
        }
    }
}

/// Verify: proposal is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_vote_constraint_0() {
    let account: SymbolicVote = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: proposal is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'proposal is writable  /* Account marked as mutable */' */ }, "Invariant violation: proposal is writable  /* Account marked as mutable */");
}

/// Verify: voter.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_vote_constraint_1() {
    let account: SymbolicVote = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: voter.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ voter.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: voter.is_signer == true  /* Anchor Signer type enforces signer check */");
}

