//! Kani proof harness for Solana account: Withdraw
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 1

/// Symbolic representation of the Solana account for verification
struct SymbolicWithdraw {
    vault: u64,
    authority: u64,
}

impl kani::Arbitrary for SymbolicWithdraw {
    fn any() -> Self {
        Self {
            vault: kani::any(),
            authority: kani::any(),
        }
    }
}

/// Verify: vault is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_withdraw_constraint_0() {
    let account: SymbolicWithdraw = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: vault is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'vault is writable  /* Account marked as mutable */' */ }, "Invariant violation: vault is writable  /* Account marked as mutable */");
}

