//! Kani proof: Bounds check for `Vault`
//! Auto-generated by kani-verifier — DO NOT EDIT
//! Source: lib.rs:182
//! Invariant: Account 'Vault' balance fields (total_deposits, total_shares) must be within valid range [0, u64::MAX]

#[cfg(kani)]
mod kani_proofs {
    /// Verify that protocol-defined bounds are respected
    #[kani::proof]
    #[kani::unwind(8)]
    fn proof_vault_balance_fields_bounded() {
        let value: u64 = kani::any();
        let max_allowed: u64 = kani::any();
        let min_allowed: u64 = kani::any();

        // Realistic protocol constraints
        kani::assume(min_allowed <= max_allowed);
        kani::assume(max_allowed <= u64::MAX / 2);

        // Invariant: value must be within [min, max]
        let in_bounds = value >= min_allowed && value <= max_allowed;

        // If bounds check is performed
        if in_bounds {
            kani::assert(value >= min_allowed, "Value below minimum");
            kani::assert(value <= max_allowed, "Value above maximum");
        }

        // Verify that out-of-bounds values are rejected
        if value > max_allowed {
            kani::assert(!in_bounds, "Out-of-bounds value not rejected (above max)");
        }
        if value < min_allowed {
            kani::assert(!in_bounds, "Out-of-bounds value not rejected (below min)");
        }
    }

    /// Verify fee/basis-point bounds (common in DeFi)
    #[kani::proof]
    #[kani::unwind(4)]
    fn proof_vault_balance_fields_bounded_fee_bps() {
        let fee_bps: u16 = kani::any();  // Basis points (0-10000)
        let amount: u64 = kani::any();

        kani::assume(fee_bps <= 10000);
        kani::assume(amount > 0 && amount <= 1_000_000_000_000u64);

        // Fee calculation must not overflow
        let fee = (amount as u128).checked_mul(fee_bps as u128);
        if let Some(fee_val) = fee {
            let fee_result = fee_val / 10000u128;
            kani::assert(fee_result <= amount as u128, "Fee exceeds principal amount");
            kani::assert(fee_result <= u64::MAX as u128, "Fee overflows u64");
        }
    }
}
