//! Kani proof harness for Solana account: Swap
//! Auto-generated by kani-verifier — DO NOT EDIT
//!
//! Source: lib.rs
//! Constraints checked: 3

/// Symbolic representation of the Solana account for verification
struct SymbolicSwap {
    source_vault: u64,
    dest_vault: u64,
    authority: u64,
}

impl kani::Arbitrary for SymbolicSwap {
    fn any() -> Self {
        Self {
            source_vault: kani::any(),
            dest_vault: kani::any(),
            authority: kani::any(),
        }
    }
}

/// Verify: source_vault is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_swap_constraint_0() {
    let account: SymbolicSwap = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: source_vault is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'source_vault is writable  /* Account marked as mutable */' */ }, "Invariant violation: source_vault is writable  /* Account marked as mutable */");
}

/// Verify: dest_vault is writable  /* Account marked as mutable */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_swap_constraint_1() {
    let account: SymbolicSwap = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: dest_vault is writable  /* Account marked as mutable */
    kani::assert({ let _ = &account; true /* TODO: encode 'dest_vault is writable  /* Account marked as mutable */' */ }, "Invariant violation: dest_vault is writable  /* Account marked as mutable */");
}

/// Verify: authority.is_signer == true  /* Anchor Signer type enforces signer check */
#[cfg(kani)]
#[kani::proof]
#[kani::unwind(10)]
fn proof_swap_constraint_2() {
    let account: SymbolicSwap = kani::any();

    // Preconditions: constrain symbolic values to realistic ranges

    // Postcondition: verify constraint
    // Invariant: authority.is_signer == true  /* Anchor Signer type enforces signer check */
    kani::assert({ authority.is_signer == true  /* Anchor Signer type enforces signer check */ }, "Invariant violation: authority.is_signer == true  /* Anchor Signer type enforces signer check */");
}

